const tips = {
  'protect-accounts': {
    title: 'Tips to protect your account',
    tip: {
      first: 'Use long, unique passwords (12+ characters).',
      second: 'Include upper/lowercase, numbers, and symbols.',
      third: 'Avoid common words, names, or patterns.',
      fourth: 'Never reuse passwords across sites.'
    },
    body: `     🔑 Use a Password Manager
            Securely stores and generates complex passwords.

            Tools like Bitwarden, 1Password, Dashlane, or LastPass can help.

            🧪 Enable Two-Factor Authentication (2FA)
            Adds a second layer of security (like a code sent to your phone or generated by an app like Authy or Google Authenticator).

            Prefer app-based 2FA over SMS when possible.

            🚨 Stay Vigilant
            Don’t click suspicious links in emails or texts.

            Always check the URL before logging into websites.

            Be cautious of unexpected emails asking for login details or urgent actions.

            🌐 Secure Your Network
            Use secure Wi-Fi with a strong password.

            Avoid logging into important accounts on public Wi-Fi unless using a VPN.

            🔁 Monitor for Breaches
            Use services like HaveIBeenPwned.com to check if your email/password has been exposed in breaches.

            Change passwords immediately if compromised.

            📱 Keep Devices Safe
            Use antivirus/malware protection.

            Keep systems and apps updated.

            Lock devices with a PIN, fingerprint, or facial recognition.`
  },

    'prevent-cloud-attacks': {
        title: 'Best practices to prevent cloud attacks',
        tip: {
        first: '🔒 Identity and Access Management (IAM): Follow principle of least privilege: users and services should have only the access they need.',
        second: 'Regularly audit permissions and roles.',
        third: 'Enable multi-factor authentication (MFA) for all cloud admin accounts.'
        },
        body: `🛠️ Secure Configuration
    Use tools like AWS Config, Azure Security Center, or GCP Security Command Center to monitor for misconfigurations.

    Regularly review and update firewall rules, access controls, and service settings.

    🔍 Logging and Monitoring
    Enable and monitor logs (e.g., AWS CloudTrail, GCP Cloud Audit Logs).

    Use SIEM (Security Information and Event Management) tools for real-time threat detection.

    📦 Secure Containers and Serverless Functions
    Scan container images for vulnerabilities.

    Apply runtime security policies (e.g., with tools like Falco or Aqua Security).

    Use minimal base images and avoid running containers as root.

    📤 Data Protection
    Encrypt data at rest and in transit.

    Apply strict access control to sensitive datasets.

    Use managed key services (e.g., AWS KMS, Azure Key Vault).

    🧪 Regular Penetration Testing
    Simulate attacks on cloud infrastructure to find vulnerabilities before real attackers do.

    Include cloud services, APIs, and authentication mechanisms.

    🌐 Use Trusted Providers and Stay Updated
    Choose cloud vendors with strong security compliance (e.g., ISO 27001, SOC 2).

    Stay informed on newly discovered threats and patch quickly.`
    },
    'malicious-use-network-tapping': {
        title: 'Malicious use of network tapping',
        tip: {
            overview: 'In the wrong hands, network tapping can lead to:',
            first: 'Data Interception: Emails, passwords, financial data, and messages can be read in plaintext (if unencrypted).',
            second: 'Session Hijacking: Attackers can steal authentication tokens or cookies.',
            third: 'Credential Harvesting: Especially on unencrypted or poorly encrypted networks (e.g., public Wi-Fi).',
        },
        body: `🛡️ How to Protect Against Network Tapping
                🔐 Use End-to-End Encryption
                HTTPS, SSL/TLS, SSH, and VPNs prevent attackers from reading data even if they intercept it.

                Avoid unencrypted protocols like HTTP, FTP, or Telnet.

                🛑 Detect and Prevent MITM Attacks
                Use certificate pinning in apps.

                Be wary of browser warnings about invalid certificates.

                Monitor ARP tables and use dynamic ARP inspection where supported.

                🧠 Monitor for Abnormal Behavior
                Use Intrusion Detection Systems (IDS) and Intrusion Prevention Systems (IPS).

                Watch for unexpected traffic mirroring or duplicated packets.

                🧰 Secure Network Infrastructure
                Lock down physical access to network equipment.

                Disable unused switch ports and monitor for rogue devices.

                Segment the network to isolate sensitive systems.

                🌐 Use VPNs on Public Networks
                Encrypts your data before it leaves your device, making sniffing ineffective on open Wi-Fi.
                `
    },
    'risks-wirless-net-pirating': {
        title: 'Risks of wireless networking pirating',
        tip: {
            first: 'Hide or Restrict Access. SSID Hiding: Makes your network name invisible (obscure, but not secure—still detectable by determined attackers).',
            second: 'MAC Address Filtering: Allows only specific devices to connect. Note: This can be bypassed by spoofing, but adds a layer of defense.',
            third: 'Guest Network: Use this for visitors; keep it separate from your main devices.',
        },
        body: `🛡️ How to Prevent Wireless Network Pirating
                ✅ Secure Your Wi-Fi Settings
                Use WPA3 encryption (or at least WPA2). Never use WEP—it's outdated and easily cracked.

                Strong Wi-Fi password: Use a long, complex passphrase. Avoid defaults.

                Change default router login (admin/admin is a huge risk).

                Disable WPS (Wi-Fi Protected Setup): This feature is vulnerable to brute-force attacks.

                🕵️‍♂️ Monitor Your Network
                Regularly log in to your router and check the connected devices list.

                Use tools like:

                Fing (mobile app)

                GlassWire (PC)

                Wireshark (advanced analysis)

                Set alerts if unknown devices connect.

                🔁 Regularly Update Firmware
                Keep your router's software up to date to patch vulnerabilities.

                🧱 Use a Firewall
                Either on your router or individual devices, a firewall can help block unwanted access attempts.

                🌐 Consider Mesh or Enterprise Wi-Fi Solutions
                Advanced systems like Ubiquiti UniFi or TP-Link Omada offer better security, alerts, and visibility for home or small business networks.
                `
    }
};

export default tips;
